name: Trigger Other Repo Action

on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read config file
        id: read-config
        run: |
          while IFS=: read -r key value; do
            key=$(echo $key | xargs)
            value=$(echo $value | xargs)
            echo "$key=$value" >> $GITHUB_ENV
          done < mainConfig.txt

      - name: Use dictionary variables
        run: |
          echo "Value for ortools-branch: $ortools-branch"
          echo "Value for is_prerelease: $is_prerelease"
