name: Trigger Other Repo Action

on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Trigger Action in Other Repo
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/proshkin/SkedAIServer/dispatches" \
            --data '{"event_type": "build_trigger", "client_payload": {"key": "value"}}'
